baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "KM Authorized"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  favicon = "favicon-32x32.svg"

  [params.homepage]
    show_contact_box = true       # show / hide the contaxt box on the homepage
    show_services_button = false  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo.svg"
    mobile_height = "39px"
    desktop = "images/logo/logo.svg"
    desktop_height = "59px"
    alt = "KM Authorized"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#217BE8"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@kmauthorized"
    meta_twitter_creator = "@keegoid"
    meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '&copy; 2024 <a class="zerostatic" href="https://kmauthorized.com">KM Authorized LLC</a>'

[menu]
  # Main Menu
#  [[menu.main]]
#    name = "Services"
#    url = "/services/"
#    weight = 1

#  [[menu.main]]
#    name = "Team"
#    url = "/team/"
#    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

 [[menu.main]]
   name = "Contact"
   url = "/contact/"
   weight = 4

  # Footer Menu
#  [[menu.footer]]
#    name = "Home"
#    url = "/"
#    weight = 1

 [[menu.footer]]
   name = "Contact"
   url = "/contact/"
   weight = 2
